application:
  unavailable-url-prefix: /out-of-area
  ping-url: http://localhost:8081/ping
#  notify-url: http://sms-service/send-sms
  notify-url: http://localhost:8081/send-sms
  ping-sleep-in-minutes: 15
  default-notify-language: ru
  default-notify-country: RU

logging:
  level.ru: debug